### ISSUE TITLE
docker: Erro response from daemon: Conflict.

### ISSUE THREAD

**Issue by RodolVelasco** [ankitrgadiya/docker-c9#1]
Hi Ankit.

I'm getting this error:
```
luis.velasco2@is-di-dev-endpoints:/var/www/html$ sudo docker run --name c9 -p 3000:3000 -d ankitrgadiya/c9
docker: Error response from daemon: Conflict. The container name "/c9" is already in use by container "429a90893c1adcb1bb0c9dbec274c272722409ff10969a04a7cb31ce317add17". You have to remove (or rename) that container to be able to reuse that name.
```
This happened when restart my VM. If I execute:
```
luis.velasco2@is-di-dev-endpoints:/var/www/html$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
luis.velasco2@is-di-dev-endpoints:/var/www/html$
```
Any idea?

**Comment by RodolVelasco** [comment]
I had to remove docker container and rerun it again with
But first I had to run:
`sudo docker ps -a`
Then:
`sudo docker rm CONTAINER_ID`

Thanks

**Comment by ankitrgadiya** [comment]
Did you had a container with the name "c9" earlier?
`docker ps` once shows the containers running currently, to list all the containers including those which are not running right now add `--all` flag.

**Comment by RodolVelasco** [comment]
Yes, I added c9 part. When I executed `docker ps` no container was running. Then I executed with `-a` argument and the container appeared. I had to remove it and then make it run again.
